apiVersion: apps/v1
kind: Deployment
metadata: 
	name: dotnet-app-deployment
	labels: 
		app: dotnet-app
spec:
	replicas: 4
	selector:
		matchLabels:
			app: dotnet-app
	template:
		metadata:
			labels:
				app: dotnet-app
		spec:
			containers:
				- name: dotnet-app
				  image: paras22/nagp-devops-assign-1	
				  ports: 
					- name: http
					  containerPort: 80
					  protocol: TCP
-----------
apiVersion: v1
kind: Service
metadata: 
	name: dotnet-app
spec:
	type:LoadBalancer
	selector: 
		app: dotnet-app
	ports
	- protocol: TCP
	  nodePort: 30158
	  port: 80
	  targetPort:80
